name: PRADA3D_env
channels:
  - pytorch
  - nvidia
  - pytorch3d
dependencies:
  - python=3.10.13
  - pip=23.3.1
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - tqdm
  - tensorboard
  - scipy
  - pytorch3d
  - open3d
  - pip:
    - opencv-python
    - lpips
    - trimesh
    - numpy==1.23.1
    - kornia
    - chumpy
